[package]
name = "af-core"
version = "0.1.0-pre.1"
edition = "2024"

[dependencies]
derive-new = "0.7.0"
derive_builder = "0.20.2"
getset = "0.1.6"
serde_json = "1.0.149"
thiserror = "2.0.18"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
